// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxfpasvxqhqyubtpjlkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94ZnBhc3Z4cWhxeXVidHBqbGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDU4OTgsImV4cCI6MjA2MzU4MTg5OH0.Glk7TybBy0zLTGvrWiCepD93mmQRMwas7LvOGhw1rdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);